import type { ProxySourceConfig } from './types';

export const DEFAULT_SOURCES: ProxySourceConfig[] = [
  {
    id: 'iplocate-all',
    name: 'IPLocate Global Free Proxies',
    url: 'https://raw.githubusercontent.com/iplocate/free-proxy-list/main/all-proxies.txt',
    format: 'text_lines',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  {
    id: 'proxifly-all',
    name: 'Proxifly Free Proxies',
    url: 'https://raw.githubusercontent.com/proxifly/free-proxy-list/main/proxies/all/data.txt',
    format: 'text_lines',
    fetchIntervalMinutes: 5,
    enabled: true,
  },
  {
    id: 'thespeedx-http',
    name: 'TheSpeedX HTTP Proxies',
    url: 'https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/http.txt',
    format: 'text_lines',
    defaultProtocol: 'http',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  {
    id: 'thespeedx-socks4',
    name: 'TheSpeedX SOCKS4 Proxies',
    url: 'https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks4.txt',
    format: 'text_lines',
    defaultProtocol: 'socks4',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  {
    id: 'thespeedx-socks5',
    name: 'TheSpeedX SOCKS5 Proxies',
    url: 'https://raw.githubusercontent.com/TheSpeedX/PROXY-List/master/socks5.txt',
    format: 'text_lines',
    defaultProtocol: 'socks5',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  // --- Monosans (Hourly, Multi-Protocol) ---
  {
    id: 'monosans-all',
    name: 'Monosans Multi-Protocol',
    url: 'https://raw.githubusercontent.com/monosans/proxy-list/main/proxies/all.txt',
    format: 'text_lines',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  // --- Komutan234 (Fast Refresh - 5min) ---
  {
    id: 'komutan-http',
    name: 'Komutan Fast HTTP',
    url: 'https://raw.githubusercontent.com/komutan234/Proxy-List-Free/main/proxies/http.txt',
    format: 'text_lines',
    defaultProtocol: 'http',
    fetchIntervalMinutes: 5,
    enabled: true,
  },
  {
    id: 'komutan-socks4',
    name: 'Komutan Fast SOCKS4',
    url: 'https://raw.githubusercontent.com/komutan234/Proxy-List-Free/main/proxies/socks4.txt',
    format: 'text_lines',
    defaultProtocol: 'socks4',
    fetchIntervalMinutes: 5,
    enabled: true,
  },
  {
    id: 'komutan-socks5',
    name: 'Komutan Fast SOCKS5',
    url: 'https://raw.githubusercontent.com/komutan234/Proxy-List-Free/main/proxies/socks5.txt',
    format: 'text_lines',
    defaultProtocol: 'socks5',
    fetchIntervalMinutes: 5,
    enabled: true,
  },
  {
    id: 'komutan-all',
    name: 'Komutan Fast All-Protocols',
    url: 'https://raw.githubusercontent.com/komutan234/Proxy-List-Free/main/proxies/all.txt',
    format: 'text_lines',
    fetchIntervalMinutes: 5,
    enabled: true,
  },
  // --- ProxyScrape Live API (Realtime) ---
  {
    id: 'proxyscrape-http',
    name: 'ProxyScrape Live HTTP',
    url: 'https://api.proxyscrape.com/v2/?request=displayproxies&protocol=http&timeout=10000&country=all&ssl=all&anonymity=all',
    format: 'text_lines',
    defaultProtocol: 'http',
    fetchIntervalMinutes: 15,
    enabled: true,
  },
  {
    id: 'proxyscrape-socks4',
    name: 'ProxyScrape Live SOCKS4',
    url: 'https://api.proxyscrape.com/v2/?request=displayproxies&protocol=socks4&timeout=10000&country=all',
    format: 'text_lines',
    defaultProtocol: 'socks4',
    fetchIntervalMinutes: 15,
    enabled: true,
  },
  {
    id: 'proxyscrape-socks5',
    name: 'ProxyScrape Live SOCKS5',
    url: 'https://api.proxyscrape.com/v2/?request=displayproxies&protocol=socks5&timeout=10000&country=all',
    format: 'text_lines',
    defaultProtocol: 'socks5',
    fetchIntervalMinutes: 15,
    enabled: true,
  },
  // --- GeoNode Live REST API (JSON, Realtime Database) ---
  {
    id: 'geonode-page1',
    name: 'GeoNode Live Proxies (Page 1)',
    url: 'https://proxylist.geonode.com/api/proxy-list?limit=500&page=1&sort_by=lastChecked&sort_type=desc',
    format: 'json',
    fetchIntervalMinutes: 15,
    enabled: true,
  },
  {
    id: 'geonode-page2',
    name: 'GeoNode Live Proxies (Page 2)',
    url: 'https://proxylist.geonode.com/api/proxy-list?limit=500&page=2&sort_by=lastChecked&sort_type=desc',
    format: 'json',
    fetchIntervalMinutes: 15,
    enabled: true,
  },
  {
    id: 'geonode-page3',
    name: 'GeoNode Live Proxies (Page 3)',
    url: 'https://proxylist.geonode.com/api/proxy-list?limit=500&page=3&sort_by=lastChecked&sort_type=desc',
    format: 'json',
    fetchIntervalMinutes: 15,
    enabled: true,
  },
  {
    id: 'geonode-page4',
    name: 'GeoNode Live Proxies (Page 4)',
    url: 'https://proxylist.geonode.com/api/proxy-list?limit=500&page=4&sort_by=lastChecked&sort_type=desc',
    format: 'json',
    fetchIntervalMinutes: 15,
    enabled: true,
  },
  {
    id: 'geonode-page5',
    name: 'GeoNode Live Proxies (Page 5)',
    url: 'https://proxylist.geonode.com/api/proxy-list?limit=500&page=5&sort_by=lastChecked&sort_type=desc',
    format: 'json',
    fetchIntervalMinutes: 15,
    enabled: true,
  },
  // --- Hookzof Dedicated SOCKS5 ---
  {
    id: 'hookzof-socks5',
    name: 'Hookzof SOCKS5',
    url: 'https://raw.githubusercontent.com/hookzof/socks5_list/master/proxy.txt',
    format: 'text_lines',
    defaultProtocol: 'socks5',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  // --- Proxmint (30-min Real HTTP Verified) ---
  {
    id: 'proxmint-http',
    name: 'Proxmint Verified HTTP',
    url: 'https://raw.githubusercontent.com/proxmint/free-proxy-list/main/proxies/http.txt',
    format: 'text_lines',
    defaultProtocol: 'http',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  {
    id: 'proxmint-socks5',
    name: 'Proxmint Verified SOCKS5',
    url: 'https://raw.githubusercontent.com/proxmint/free-proxy-list/main/proxies/socks5.txt',
    format: 'text_lines',
    defaultProtocol: 'socks5',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  // --- Roosterkid OpenProxyList (Hourly) ---
  {
    id: 'roosterkid-http',
    name: 'Roosterkid HTTP',
    url: 'https://raw.githubusercontent.com/roosterkid/openproxylist/main/HTTP_RAW.txt',
    format: 'text_lines',
    defaultProtocol: 'http',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  {
    id: 'roosterkid-https',
    name: 'Roosterkid HTTPS',
    url: 'https://raw.githubusercontent.com/roosterkid/openproxylist/main/HTTPS_RAW.txt',
    format: 'text_lines',
    defaultProtocol: 'https',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  {
    id: 'roosterkid-socks4',
    name: 'Roosterkid SOCKS4',
    url: 'https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS4_RAW.txt',
    format: 'text_lines',
    defaultProtocol: 'socks4',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  {
    id: 'roosterkid-socks5',
    name: 'Roosterkid SOCKS5',
    url: 'https://raw.githubusercontent.com/roosterkid/openproxylist/main/SOCKS5_RAW.txt',
    format: 'text_lines',
    defaultProtocol: 'socks5',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  // --- ErcinDedeoglu Proxies (Updated Hourly, 100k+ Proxies) ---
  {
    id: 'ercin-http',
    name: 'ErcinDedeoglu HTTP Proxies',
    url: 'https://raw.githubusercontent.com/ErcinDedeoglu/proxies/main/proxies/http.txt',
    format: 'text_lines',
    defaultProtocol: 'http',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  {
    id: 'ercin-socks4',
    name: 'ErcinDedeoglu SOCKS4 Proxies',
    url: 'https://raw.githubusercontent.com/ErcinDedeoglu/proxies/main/proxies/socks4.txt',
    format: 'text_lines',
    defaultProtocol: 'socks4',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  {
    id: 'ercin-socks5',
    name: 'ErcinDedeoglu SOCKS5 Proxies',
    url: 'https://raw.githubusercontent.com/ErcinDedeoglu/proxies/main/proxies/socks5.txt',
    format: 'text_lines',
    defaultProtocol: 'socks5',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  // --- KangProxy / OfficialPutuID (Updated Hourly) ---
  {
    id: 'kangproxy-http',
    name: 'KangProxy HTTP',
    url: 'https://raw.githubusercontent.com/officialputuid/KangProxy/main/http/http.txt',
    format: 'text_lines',
    defaultProtocol: 'http',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  {
    id: 'kangproxy-https',
    name: 'KangProxy HTTPS',
    url: 'https://raw.githubusercontent.com/officialputuid/KangProxy/main/https/https.txt',
    format: 'text_lines',
    defaultProtocol: 'https',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  {
    id: 'kangproxy-socks4',
    name: 'KangProxy SOCKS4',
    url: 'https://raw.githubusercontent.com/officialputuid/KangProxy/main/socks4/socks4.txt',
    format: 'text_lines',
    defaultProtocol: 'socks4',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  {
    id: 'kangproxy-socks5',
    name: 'KangProxy SOCKS5',
    url: 'https://raw.githubusercontent.com/officialputuid/KangProxy/main/socks5/socks5.txt',
    format: 'text_lines',
    defaultProtocol: 'socks5',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  // --- dpangestuw Free-Proxy (Updated Hourly) ---
  {
    id: 'dpangestuw-http',
    name: 'Dpangestuw HTTP Proxies',
    url: 'https://raw.githubusercontent.com/dpangestuw/Free-Proxy/main/http_proxies.txt',
    format: 'text_lines',
    defaultProtocol: 'http',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  {
    id: 'dpangestuw-socks4',
    name: 'Dpangestuw SOCKS4 Proxies',
    url: 'https://raw.githubusercontent.com/dpangestuw/Free-Proxy/main/socks4_proxies.txt',
    format: 'text_lines',
    defaultProtocol: 'socks4',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  {
    id: 'dpangestuw-socks5',
    name: 'Dpangestuw SOCKS5 Proxies',
    url: 'https://raw.githubusercontent.com/dpangestuw/Free-Proxy/main/socks5_proxies.txt',
    format: 'text_lines',
    defaultProtocol: 'socks5',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  // --- Sunny9577 Scraper Lists ---
  {
    id: 'sunny9577-http',
    name: 'Sunny9577 Scraped HTTP',
    url: 'https://raw.githubusercontent.com/sunny9577/proxy-scraper/master/generated/http_proxies.txt',
    format: 'text_lines',
    defaultProtocol: 'http',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  {
    id: 'sunny9577-socks5',
    name: 'Sunny9577 Scraped SOCKS5',
    url: 'https://raw.githubusercontent.com/sunny9577/proxy-scraper/master/generated/socks5_proxies.txt',
    format: 'text_lines',
    defaultProtocol: 'socks5',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  // --- Spys.me Live Lists (Hourly) ---
  {
    id: 'spysme-http',
    name: 'Spys.me HTTP',
    url: 'http://spys.me/proxy.txt',
    format: 'text_lines',
    defaultProtocol: 'http',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  {
    id: 'spysme-socks',
    name: 'Spys.me SOCKS',
    url: 'http://spys.me/socks.txt',
    format: 'text_lines',
    defaultProtocol: 'socks5',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  // --- Anonym0usWork1221 (Hourly Refreshed) ---
  {
    id: 'anonym0uswork-http',
    name: 'Anonym0usWork HTTP Proxies',
    url: 'https://raw.githubusercontent.com/Anonym0usWork1221/Free-Proxies/main/proxy_files/http_proxies.txt',
    format: 'text_lines',
    defaultProtocol: 'http',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  {
    id: 'anonym0uswork-https',
    name: 'Anonym0usWork HTTPS Proxies',
    url: 'https://raw.githubusercontent.com/Anonym0usWork1221/Free-Proxies/main/proxy_files/https_proxies.txt',
    format: 'text_lines',
    defaultProtocol: 'https',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  {
    id: 'anonym0uswork-socks4',
    name: 'Anonym0usWork SOCKS4 Proxies',
    url: 'https://raw.githubusercontent.com/Anonym0usWork1221/Free-Proxies/main/proxy_files/socks4_proxies.txt',
    format: 'text_lines',
    defaultProtocol: 'socks4',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  {
    id: 'anonym0uswork-socks5',
    name: 'Anonym0usWork SOCKS5 Proxies',
    url: 'https://raw.githubusercontent.com/Anonym0usWork1221/Free-Proxies/main/proxy_files/socks5_proxies.txt',
    format: 'text_lines',
    defaultProtocol: 'socks5',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  // --- ObcbO GetProxy (Hourly Refreshed) ---
  {
    id: 'obcbo-http',
    name: 'ObcbO HTTP Proxies',
    url: 'https://raw.githubusercontent.com/ObcbO/getproxy/master/file/http.txt',
    format: 'text_lines',
    defaultProtocol: 'http',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  {
    id: 'obcbo-https',
    name: 'ObcbO HTTPS Proxies',
    url: 'https://raw.githubusercontent.com/ObcbO/getproxy/master/file/https.txt',
    format: 'text_lines',
    defaultProtocol: 'https',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  {
    id: 'obcbo-socks4',
    name: 'ObcbO SOCKS4 Proxies',
    url: 'https://raw.githubusercontent.com/ObcbO/getproxy/master/file/socks4.txt',
    format: 'text_lines',
    defaultProtocol: 'socks4',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  {
    id: 'obcbo-socks5',
    name: 'ObcbO SOCKS5 Proxies',
    url: 'https://raw.githubusercontent.com/ObcbO/getproxy/master/file/socks5.txt',
    format: 'text_lines',
    defaultProtocol: 'socks5',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  // --- HideIP.me / Zloi-user (Hourly Verified) ---
  {
    id: 'zloi-http',
    name: 'HideIP.me HTTP Proxies',
    url: 'https://raw.githubusercontent.com/zloi-user/hideip.me/main/http.txt',
    format: 'text_lines',
    defaultProtocol: 'http',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  {
    id: 'zloi-https',
    name: 'HideIP.me HTTPS Proxies',
    url: 'https://raw.githubusercontent.com/zloi-user/hideip.me/main/https.txt',
    format: 'text_lines',
    defaultProtocol: 'https',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  {
    id: 'zloi-socks4',
    name: 'HideIP.me SOCKS4 Proxies',
    url: 'https://raw.githubusercontent.com/zloi-user/hideip.me/main/socks4.txt',
    format: 'text_lines',
    defaultProtocol: 'socks4',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  {
    id: 'zloi-socks5',
    name: 'HideIP.me SOCKS5 Proxies',
    url: 'https://raw.githubusercontent.com/zloi-user/hideip.me/main/socks5.txt',
    format: 'text_lines',
    defaultProtocol: 'socks5',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  // --- Vakhov Fresh Proxy List (Hourly Automated) ---
  {
    id: 'vakhov-http',
    name: 'Vakhov Fresh HTTP',
    url: 'https://raw.githubusercontent.com/vakhov/fresh-proxy-list/master/http.txt',
    format: 'text_lines',
    defaultProtocol: 'http',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  {
    id: 'vakhov-socks4',
    name: 'Vakhov Fresh SOCKS4',
    url: 'https://raw.githubusercontent.com/vakhov/fresh-proxy-list/master/socks4.txt',
    format: 'text_lines',
    defaultProtocol: 'socks4',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  {
    id: 'vakhov-socks5',
    name: 'Vakhov Fresh SOCKS5',
    url: 'https://raw.githubusercontent.com/vakhov/fresh-proxy-list/master/socks5.txt',
    format: 'text_lines',
    defaultProtocol: 'socks5',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  // --- Tuanminpay Live Proxy (Active Multi-Protocol) ---
  {
    id: 'tuanminpay-http',
    name: 'Tuanminpay Live HTTP',
    url: 'https://raw.githubusercontent.com/tuanminpay/live-proxy/master/http.txt',
    format: 'text_lines',
    defaultProtocol: 'http',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  {
    id: 'tuanminpay-socks4',
    name: 'Tuanminpay Live SOCKS4',
    url: 'https://raw.githubusercontent.com/tuanminpay/live-proxy/master/socks4.txt',
    format: 'text_lines',
    defaultProtocol: 'socks4',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  {
    id: 'tuanminpay-socks5',
    name: 'Tuanminpay Live SOCKS5',
    url: 'https://raw.githubusercontent.com/tuanminpay/live-proxy/master/socks5.txt',
    format: 'text_lines',
    defaultProtocol: 'socks5',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  // --- ALIILAPRO Proxy (Multi-Protocol) ---
  {
    id: 'aliilapro-http',
    name: 'ALIILAPRO HTTP Proxies',
    url: 'https://raw.githubusercontent.com/ALIILAPRO/Proxy/main/http.txt',
    format: 'text_lines',
    defaultProtocol: 'http',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  {
    id: 'aliilapro-socks4',
    name: 'ALIILAPRO SOCKS4 Proxies',
    url: 'https://raw.githubusercontent.com/ALIILAPRO/Proxy/main/socks4.txt',
    format: 'text_lines',
    defaultProtocol: 'socks4',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  {
    id: 'aliilapro-socks5',
    name: 'ALIILAPRO SOCKS5 Proxies',
    url: 'https://raw.githubusercontent.com/ALIILAPRO/Proxy/main/socks5.txt',
    format: 'text_lines',
    defaultProtocol: 'socks5',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  // --- Elliottophellia Yakumo (Checked Global Proxies) ---
  {
    id: 'yakumo-http',
    name: 'Yakumo Checked HTTP',
    url: 'https://raw.githubusercontent.com/elliottophellia/yakumo/master/results/http/global/http_checked.txt',
    format: 'text_lines',
    defaultProtocol: 'http',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  {
    id: 'yakumo-socks4',
    name: 'Yakumo Checked SOCKS4',
    url: 'https://raw.githubusercontent.com/elliottophellia/yakumo/master/results/socks4/global/socks4_checked.txt',
    format: 'text_lines',
    defaultProtocol: 'socks4',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  {
    id: 'yakumo-socks5',
    name: 'Yakumo Checked SOCKS5',
    url: 'https://raw.githubusercontent.com/elliottophellia/yakumo/master/results/socks5/global/socks5_checked.txt',
    format: 'text_lines',
    defaultProtocol: 'socks5',
    fetchIntervalMinutes: 30,
    enabled: true,
  },
  // --- VPSLab Cloud Free Proxy List (Refreshed Every 15 Minutes) ---
  {
    id: 'vpslab-http',
    name: 'VPSLab Fresh HTTP (15m)',
    url: 'https://raw.githubusercontent.com/VPSLabCloud/VPSLab-Free-Proxy-List/main/http_all.txt',
    format: 'text_lines',
    defaultProtocol: 'http',
    fetchIntervalMinutes: 15,
    enabled: true,
  },
  {
    id: 'vpslab-socks4',
    name: 'VPSLab Fresh SOCKS4 (15m)',
    url: 'https://raw.githubusercontent.com/VPSLabCloud/VPSLab-Free-Proxy-List/main/socks4_all.txt',
    format: 'text_lines',
    defaultProtocol: 'socks4',
    fetchIntervalMinutes: 15,
    enabled: true,
  },
  {
    id: 'vpslab-socks5',
    name: 'VPSLab Fresh SOCKS5 (15m)',
    url: 'https://raw.githubusercontent.com/VPSLabCloud/VPSLab-Free-Proxy-List/main/socks5_all.txt',
    format: 'text_lines',
    defaultProtocol: 'socks5',
    fetchIntervalMinutes: 15,
    enabled: true,
  },
  {
    id: 'vpslab-elite',
    name: 'VPSLab Fresh Elite (15m)',
    url: 'https://raw.githubusercontent.com/VPSLabCloud/VPSLab-Free-Proxy-List/main/all_elite.txt',
    format: 'text_lines',
    defaultProtocol: 'http',
    fetchIntervalMinutes: 15,
    enabled: true,
  },
  // --- ProxRipper (Massive 30k+ proxies, Refreshed Every 15 Minutes) ---
  {
    id: 'proxripper-http',
    name: 'ProxRipper Fresh HTTP (15m)',
    url: 'https://raw.githubusercontent.com/Mohammedcha/ProxRipper/main/full_proxies/http.txt',
    format: 'text_lines',
    defaultProtocol: 'http',
    fetchIntervalMinutes: 15,
    enabled: true,
  },
  {
    id: 'proxripper-socks5',
    name: 'ProxRipper Fresh SOCKS5 (15m)',
    url: 'https://raw.githubusercontent.com/Mohammedcha/ProxRipper/main/full_proxies/socks5.txt',
    format: 'text_lines',
    defaultProtocol: 'socks5',
    fetchIntervalMinutes: 15,
    enabled: true,
  },
];

export const APP_CONFIG = {
  PORT: Number(process.env.PORT || 8340),
  HOST: process.env.HOST || '0.0.0.0',
  DB_PATH: process.env.DB_PATH || 'data/proxies.db',

  // Pyramid Lifecycle & Concurrency
  MAINTENANCE_INTERVAL_MINUTES: Number(process.env.MAINTENANCE_INTERVAL_MINUTES || 3),
  CONCURRENCY_LIMIT: Number(process.env.CONCURRENCY_LIMIT || 300),
  TIMEOUT_MS: Number(process.env.TIMEOUT_MS || 1800),
  MAX_CONSECUTIVE_FAILS: Number(process.env.MAX_CONSECUTIVE_FAILS || 2),

  // Producer-Consumer Basket & Deduplication
  DEDUP_COOLDOWN_MINUTES: Number(process.env.DEDUP_COOLDOWN_MINUTES || 3),
  SCREENING_BATCH_SIZE: Number(process.env.SCREENING_BATCH_SIZE || 600),

  // High-availability Fast Echo Targets (Rotated to avoid any rate limits)
  TARGET_URLS: [
    'https://cloudflare.com/cdn-cgi/trace',
    'https://api.ipify.org?format=json',
    'https://icanhazip.com',
    'https://httpbin.org/ip',
  ],
};
